In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3,4,5])

In [3]:
print(a)


[1 2 3 4 5]


In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
b=np.array([[1,2,3],[4,5,6]])

In [7]:
a.shape

(5,)

In [8]:
b.shape

(2, 3)

In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [12]:
a.dtype
b.dtype

dtype('int32')

In [13]:
z=np.array([1,2,3,4,5],dtype=float)

In [14]:
z

array([1., 2., 3., 4., 5.])

In [15]:
z.dtype

dtype('float64')

In [16]:
#array opertions
print("array addition:", a+2)

array addition: [3 4 5 6 7]


In [17]:
print("array addition:", b+2)

array addition: [[3 4 5]
 [6 7 8]]


In [18]:
print("array addition:", a*2)

array addition: [ 2  4  6  8 10]


In [20]:
np.mean(a)

3.0

In [21]:
np.std(b)

1.707825127659933

In [22]:
np.mean(b)

3.5

In [23]:
c=a.reshape(5,1)

In [24]:
c

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [25]:
d=np.array([[1,2],[3,4],[5,6]])

In [26]:
d.shape

(3, 2)

In [27]:
np.dot(b,d)

array([[22, 28],
       [49, 64]])

In [28]:
f=np.array([3,5,6,2,2])

In [29]:
np.dot(a,f)

49

In [32]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
np.ones((3,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [36]:
d=np.arange(0,100,5)

In [37]:
d

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [38]:
k=np.linspace(0,10,4)

In [39]:
k

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [40]:
r=np.random.rand(2,3)

In [41]:
r

array([[0.30987929, 0.31260357, 0.3259025 ],
       [0.25441945, 0.3790453 , 0.16510981]])

In [44]:
y=np.concatenate((a,d))

In [45]:
y

array([ 1,  2,  3,  4,  5,  0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55,
       60, 65, 70, 75, 80, 85, 90, 95])

In [49]:
x=np.split(y,5)

In [50]:
x

[array([1, 2, 3, 4, 5]),
 array([ 0,  5, 10, 15, 20]),
 array([25, 30, 35, 40, 45]),
 array([50, 55, 60, 65, 70]),
 array([75, 80, 85, 90, 95])]